# Generated by Django 4.2.9 on 2026-02-11 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL to be shortened', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Unique short code identifier', max_length=10, unique=True)),
                ('custom_code', models.BooleanField(default=False, help_text='True if custom alias, False if auto-generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when URL was created')),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration date for the URL', null=True)),
                ('click_count', models.IntegerField(default=0, help_text='Total number of clicks (cached, updated by Celery)')),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='urls_short_c_484089_idx'), models.Index(fields=['expiry_date'], name='urls_expiry__f540b4_idx'), models.Index(fields=['-created_at'], name='urls_created_c45421_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the click occurred')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the requester')),
                ('user_agent', models.TextField(help_text='User agent string from the request')),
                ('url', models.ForeignKey(help_text='The URL that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.url')),
            ],
            options={
                'db_table': 'click_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['url', '-timestamp'], name='click_event_url_id_c11690_idx'), models.Index(fields=['-timestamp'], name='click_event_timesta_7fc01e_idx')],
            },
        ),
    ]
